# Generated by Django 4.2.4 on 2023-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('model', models.IntegerField()),
                ('kms_ran', models.CharField(max_length=50)),
                ('engine_power', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('image_link', models.TextField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
