# Generated by Django 4.2.4 on 2023-10-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
